

	DECLARE @NUNOTA_PED INT 
	DECLARE @SEQUENCIA_ORIG INT
	DECLARE @SEQUENCIA_SAI INT
	DECLARE @CODPROD_SAI INT
	DECLARE @QTD_ATD INT
	

	IF(@TIPMOV ='V')
	BEGIN
		IF (@CODTIPOPER = 1363)
		BEGIN
			IF (@STATUSNOTA = 'A')
			BEGIN
				IF EXISTS (SELECT NUNOTA FROM TGFCAB WHERE CHAVENFEREF = @CHAVENFEREF)
				BEGIN
					SET @CODPROD_SAI = (SELECT TOP 1 CODPROD FROM  TGFITE WHERE NUNOTA= @NUNOTA)
					SET @SEQUENCIA_SAI = (SELECT SEQUENCIA FROM  TGFITE WHERE NUNOTA= @NUNOTA AND CODPROD = @CODPROD_SAI)
					SET @QTD_ATD = (SELECT QTDNEG FROM  TGFITE WHERE NUNOTA= @NUNOTA AND CODPROD = @CODPROD_SAI)
					
					SET @NUNOTA_PED = (SELECT NUNOTA FROM TGFCAB WHERE CHAVENFEREF = @CHAVENFEREF)
					SET @SEQUENCIA_ORIG = (SELECT SEQUENCIA FROM TGFITE WHERE NUNOTA = @NUNOTA_PED AND CODPROD = @CODPROD_SAI)

					INSERT INTO TGFVAR(NUNOTA,SEQUENCIA,NUNOTAORIG,SEQUENCIAORIG,QTDATENDIDA,STATUSNOTA)
					VALUES(@NUNOTA, @SEQUENCIA_SAI,@NUNOTA_PED,@SEQUENCIA_ORIG,@QTD_ATD,@STATUSNOTA)
				END
			END
		END
	END